### ISSUE TITLE
Initial commit and readme

### ISSUE THREAD

**Issue by alce65** [AldanaArcidiacono/202210-W3-WeekendChallenge-Aldana-Arcidiacono#5]
Hola Aldana.
Está muy bien incluir en el readme las instrucciones del challenge, pero si dejas una imagen, asegúrate de que el enlace sea correcto, incluyendo la imagen en el commit inicial.
El readme es la presentación del proyecto y la tuya como developer.
Si está mal, no está invitando a seguir mirando nada dentro del proyecto.
Cámbialo cuando puedas y tenlo en cuenta en el futuro

**Comment by AldanaArcidiacono** [comment]
Hola Alejandro, gracias por la correccion, no lo había notado!
Ya lo he corregido

**Comment by alce65** [comment]
Genial. Cierro el issue
